name: Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: install deps
        run: npm install
        working-directory: ./server

      - name: run tests
        run: npm run test
        working-directory: ./server